version: "3.8"

services:

  app:
    build: .
    restart: always
    container_name: api
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  db:
    container_name: database
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1989"
      MYSQL_DATABASE: pets
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE